# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18wn2phND3oysfUWAwR5UMqyrwxntEard
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error

df = pd.read_csv(
    "AirPassengers.csv",
    parse_dates=['Month'],
    index_col='Month'
)

print(df.head())

print(df.columns)

df.rename(columns={'Passengers':'Passengers'}, inplace=True)

df.head()

"""**Resampling**"""

quarterly = df.resample('Q').mean()

print(quarterly.head())

"""**PLOT**"""

plt.figure(figsize=(12,5))
plt.plot(df)
plt.title("Air Passengers Over Time")
plt.show()

quarterly = df.resample('Q').mean()

quarterly.head()

"""**Trend & Seasonality**"""

decomposition = seasonal_decompose(
    df,
    model='multiplicative'
)

decomposition.plot()
plt.show()

df['MA_6'] = df['Passengers'].rolling(6).mean()

df.head(10)

df['MA_12'] = df['Passengers'].rolling(12).mean()

df.head(12)

plt.figure(figsize=(12,5))

plt.plot(df['Passengers'], label='Actual')
plt.plot(df['MA_6'], label='6-Month Moving Average')
plt.plot(df['MA_12'], label='12-Month Moving Average')

plt.title('Air Passengers Trend')
plt.xlabel('Year')
plt.ylabel('Passengers')
plt.legend()

plt.show()

print("Train Shape:", train.shape)
print("Test Shape:", test.shape)

"""**ARIMA Model**"""

from statsmodels.tsa.arima.model import ARIMA

model = ARIMA(train['Passengers'], order=(2,1,1))

result = model.fit()

print(result.summary())

forecast = result.forecast(steps=12)

print(forecast)

plt.figure(figsize=(12,5))

plt.plot(test, label='Actual')

plt.plot(forecast, label='Forecast')

plt.legend()

plt.show()

print(test.shape)
print(forecast.shape)

print(test.columns)

"""**RMSE**"""

rmse = np.sqrt(
    mean_squared_error(
        test['Passengers'],
        forecast
    )
)

print("RMSE:", rmse)

forecast = result.forecast(
    steps=12
)

"""**Compare Actual vs Predicted**"""

plt.figure(figsize=(12,5))

plt.plot(test, label='Actual')

plt.plot(forecast, label='Forecast')

plt.legend()

plt.show()

"""**Actual vs Forecast Plot**"""

plt.figure(figsize=(12,5))

plt.plot(test['Passengers'], label='Actual')
plt.plot(forecast, label='Forecast')

plt.title('Actual vs Forecasted Passengers')
plt.xlabel('Date')
plt.ylabel('Passengers')
plt.legend()

plt.show()

"""**Forecast Error**"""

error = test['Passengers'] - forecast

print(error.head())

"""**Mean Absolute Error (MAE)**"""

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(
    test['Passengers'],
    forecast
)

print("MAE:", mae)

"""**Passenger Growth Rate**"""

growth_rate = (
    (df['Passengers'].iloc[-1] -
     df['Passengers'].iloc[0])
    /
    df['Passengers'].iloc[0]
) * 100

print("Growth Rate:", growth_rate,"%")

"""**Monthly Trend Analysis**"""

monthly_avg = df.groupby(df.index.month)['Passengers'].mean()

print(monthly_avg)

"""**Best and Worst Month**"""

monthly_avg = df.groupby(df.index.month)['Passengers'].mean()

print("Highest Month:")
print(monthly_avg.idxmax())

print("Lowest Month:")
print(monthly_avg.idxmin())

"""**Future 12-Month Forecast Plot**"""

future_forecast = result.forecast(steps=12)

plt.figure(figsize=(12,5))

plt.plot(df['Passengers'], label='Historical Data')
plt.plot(
    future_forecast,
    label='Future Forecast'
)

plt.legend()
plt.title('Future Passenger Forecast')
plt.show()

"""**ACF & PACF Plot**"""

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

plot_acf(df['Passengers'])
plt.show()

plot_pacf(df['Passengers'])
plt.show()

"""**Year-wise Passenger Growth**"""

yearly = df['Passengers'].resample('Y').mean()

plt.figure(figsize=(10,5))
plt.plot(yearly)
plt.title("Yearly Average Passengers")
plt.show()

future_forecast = result.forecast(steps=24)

plt.figure(figsize=(12,5))
plt.plot(df['Passengers'], label='Historical')
plt.plot(future_forecast, label='Future Forecast')
plt.legend()
plt.show()

df.to_csv("cleaned_passengers.csv", index=False)

print("\nCleaned dataset saved as 'cleaned_customers.csv'")